title: Short Notion // Mark van de Korput
description: > # this means to ignore newlines until "baseurl:"
  New Media Developer, Virtual Realist, Computational Desirer
permalink: ':title/'
baseurl: "/_staging" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: shortnotion #if your site has a twitter account, enter it here

# Author Settings
author: Mark van de Korput # add your name
author-img: logo-shortnotion-400x400.png # add your photo
about-author: New Media Developer, Virtual Realist, Computational Desirer. # add description
social-twitter: shortnotion # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: markkorput # add your Github handle
social-linkedin: mark-van-de-korput-51038619 # add your Linkedin handle
social-email: shortnotion@gmail.com # add your Email address

# Disqus
# discus-identifier: markkorput # add your discus identifier

# Tracker
analytics: #UA-84011707-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 100
#paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
